version: "2"
services:
  tomcat:
    image: inikolaev/alpine-tomcat
    links:
      - mysql:mysql
    depends_on:
      - mysql
  nginx:
    image: inikolaev/alpine-nginx
    ports:
      - 80:80
    links:
      - tomcat:tomcat
    depends_on:
      - tomcat
  mysql:
    image: inikolaev/alpine-mysql
